services:
  postgres:
    image: postgres:15
    container_name: warehouse_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse_db
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
