version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: warehouse_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse_db
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
